"""Add default_thumb to Post

Revision ID: 42dc0996903d
Revises: f8bd789a6d74
Create Date: 2026-06-08 23:43:23.246323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dc0996903d'
down_revision = 'f8bd789a6d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_thumb', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('default_thumb')

    # ### end Alembic commands ###
